### ISSUE TITLE
some input giving wrong result

### ISSUE THREAD

**Issue by Anonymus0999** [nadar/stemming#2]
if there is some input like "physics", "mathematics", "geography"... giving wrong result

**Comment by nadar** [comment]
thanks, i will take a look at this. What would you suggest as expected output?

**Comment by Anonymus0999** [comment]
Thank you for your reply. I just want to say, there should be a list of word, those will be ignored.
Ignore list example: '"NEWS, PHYSICS, MATHEMATICS, GEOGRAPHY, BUS,................."

**Comment by nadar** [comment]
Okay, so you would like to have an option to ignore certain words. sure, why not :+1:

**Comment by nadar** [comment]
https://github.com/nadar/stemming/commit/0ecff82d6b9c0b73313f20eeb61505c99a2bcccc
